int32 status_word 
float32 longitude
float32 latitude  
float32 altitude                     # (m)
float32 roll_angle                   #(rad)     
float32 pitch_angle 
float32 yaw_angle 
float32 angular_rate_x               #Body frame rollrate (rad/s)     
float32 angular_rate_y               #Body frame pitchrate (rad/s)
float32 angular_rate_z               #Body frame yawrate (rad/s)
float32 north_direction_speed        #(m/s)
float32 east_direction_speed 
float32 ground_direction_speed  
float32 acceleration_x               #(m/s^2)
float32 acceleration_y
float32 acceleration_z
